import { Link } from "react-router-dom";

import { DocumentIcon } from "../components/icons";

/**
 * The front door.
 *
 * `/` without a `?class=` link is this page rather than a dashboard, because a
 * student's dashboard without a class has nothing to show. Rather than an empty
 * screen or a list of every class on the platform, it explains the one thing a
 * newcomer needs to know: a student is *sent* to their class by a link, they do
 * not go and find it.
 *
 * ## Why there is no class list here
 *
 * A directory of every class would look helpful and would be a privacy problem:
 * class names, batches and sections are real information about real students, and
 * the rules make active classes readable by anyone precisely so that *holders of
 * a link* can see them. Listing them all would undo that. So the link is the
 * only way in, and this page says so.
 *
 * The class link itself is generated by the CR in their dashboard, which is M6.
 * Nothing here has to know a class id to explain the flow.
 */

/** The two audiences, in the order a reader is most likely to be one of them. */
const AUDIENCES = [
  {
    id: "student",
    title: "I'm a student",
    body: "Ask your class representative for your class link, then open it. Everything your CR has posted shows up there — no account, no app, nothing to install.",
    action: null,
  },
  {
    id: "cr",
    title: "I'm a class representative",
    body: "Create your class board and post assignments for your class. You get a link to share with everyone; they see your posts the moment you publish them.",
    action: { to: "/cr/login", label: "CR sign in" },
  },
] as const;

export function HomePage() {
  return (
    <div className="landing">
      <div className="landing__inner">
        <header className="landing__header">
          <p className="landing__brand">
            <DocumentIcon size={22} />
            <span>classboard</span>
          </p>

          <h1 className="landing__title">
            One place for your class&rsquo;s assignments.
          </h1>

          <p className="landing__lede">
            Your class representative posts the work, the deadlines and the
            notices. You open your class link and everything they have posted is
            there &mdash; sorted by what is due, so the overdue work is at the top
            and nothing is missed.
          </p>
        </header>

        <ul className="landing__audiences">
          {AUDIENCES.map((audience) => (
            <li key={audience.id} className={`landing__card landing__card--${audience.id}`}>
              <h2 className="landing__card-title">{audience.title}</h2>
              <p className="landing__card-body">{audience.body}</p>
              {audience.action && (
                <Link className="button button--primary" to={audience.action.to}>
                  {audience.action.label}
                </Link>
              )}
            </li>
          ))}
        </ul>

        <section className="landing__how" aria-labelledby="how-it-works">
          <h2 className="landing__how-title" id="how-it-works">
            How it works
          </h2>
          <ol className="landing__steps">
            <li>
              <span className="landing__step-label">Your CR sets up the class</span>
              <span className="landing__step-body">
                They sign in and create a board for their class, with the subjects
                that class actually takes.
              </span>
            </li>
            <li>
              <span className="landing__step-label">They post an assignment</span>
              <span className="landing__step-body">
                A title, what to do, and the due date. Everyone with the link sees
                it immediately.
              </span>
            </li>
            <li>
              <span className="landing__step-label">You open the link and tick things off</span>
              <span className="landing__step-body">
                Mark work done and it stays marked on your own device. Your CR
                never sees who has finished what.
              </span>
            </li>
          </ol>
        </section>

        <footer className="landing__footer">
          <p className="landing__footnote">
            Students need no account, so there is no password to forget and
            nothing to sign up for. Signing in is only for class
            representatives and administrators.
          </p>
          <Link className="landing__admin-link" to="/admin/login">
            Administrator sign in
          </Link>
        </footer>
      </div>
    </div>
  );
}
